version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - jaeger-file-server
  go-file-server:
    restart: always
    ports:
      - 8090:8090
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/data:/go/bin/resources/LFS/
    environment:
      - FILE_SERVER_BASE_PATH=./resources/LFS/
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
    networks:
      - jaeger-file-server
networks:
  jaeger-file-server: